
using Achareh.Domain.Core.Entities.Request;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Achareh.Infrastructure.EfCore.Configurations
{
    public class HomeServiceConfiguration : IEntityTypeConfiguration<HomeService>
    {
        public void Configure(EntityTypeBuilder<HomeService> builder)
        {
            builder.HasKey(x => x.Id);
            builder.ToTable("HomeServices");
            builder.Property(x => x.Title).IsRequired().HasMaxLength(100);


            builder.HasOne(x => x.SubCategory)
               .WithMany(x => x.HomeServices)
               .HasForeignKey(x => x.SubCategoryId)
               .OnDelete(DeleteBehavior.Cascade);




            builder.HasMany(x => x.Requests)
                 .WithOne(x => x.HomeService);


            builder.HasData(new List<HomeService>()
            {
                new HomeService() { Id = 1, CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "خدمات نظافت منزل",Price=2000, SubCategoryId=1 ,ImagePath = "/images/homeservice/nezafat_manzel.jpg"},
                new HomeService() { Id = 2, CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "نظافت راه پله",Price=2000,SubCategoryId=1 , ImagePath = "/images/homeservice/nezafat_rahpele.jpg" },
                new HomeService() { Id = 3, CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "قالیشویی",Price=2000,SubCategoryId=2 ,ImagePath = "/images/homeservice/ghalishoyi.jpg" },
                new HomeService() { Id = 4, CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "پرده شویی",Price=2000,SubCategoryId=2 ,ImagePath = "/images/homeservice/pardeshoyi.jpg" },
                new HomeService() { Id = 5, CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "سرامیک خودرو",Price=2000,SubCategoryId=3 ,ImagePath = "/images/homeservice/seramik_khodro.jpg" },
                new HomeService() { Id = 6, CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "صفرشویی خودرو",Price=2000,SubCategoryId=3 ,ImagePath = "/images/homeservice/sefrshoyi_khodro.jpg" },
                new HomeService() { Id = 7, CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "تعمیر و سرویس کولر آبی",Price=2000,SubCategoryId=4 ,ImagePath = "/images/homeservice/tamir_coolerabi.jpg" },
                new HomeService() { Id = 8, CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "کانال سازی کولر",Price=2000,SubCategoryId=4 ,ImagePath = "/images/homeservice/kanalsazi_cooler.jpg" },
                new HomeService() { Id = 9, CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "تعمیر و نگهداری موتورخانه",Price=2000,SubCategoryId=4 ,ImagePath = "/images/homeservice/tamir_motorkhane.jpg" },
                new HomeService() { Id = 10,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "سنگ کاری",Price=2000,SubCategoryId=5 ,ImagePath = "/images/homeservice/sangkari.jpg" },
                new HomeService() { Id = 11,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "بنایی",Price=2000,SubCategoryId=5 ,ImagePath = "/images/homeservice/banayi.jpg" },
                new HomeService() { Id = 12,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "کلیدسازی",Price=2000,SubCategoryId=5 ,ImagePath = "/images/homeservice/klidsazi.jpg" },
                new HomeService() { Id = 13,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "کفسابی",Price=2000,SubCategoryId=5 ,ImagePath = "/images/homeservice/kafsabi.jpg" },
                new HomeService() { Id = 14,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "خدمات لوله کشی ساختمان",Price=2000,SubCategoryId=6 ,ImagePath = "/images/homeservice/lolekeshi.jpg" },
                new HomeService() { Id = 15,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "تخلیه چاه و لوله بازکنی",Price=2000,SubCategoryId=6 ,ImagePath = "/images/homeservice/lolebazkoni.jpg" },
                new HomeService() { Id = 16,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "لوله کشی آب و فاضلاب",Price=2000,SubCategoryId=6 ,ImagePath = "/images/homeservice/lolekeshi_fazelab.jpg" },
                new HomeService() { Id = 17,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "مشاوره و بازسازی ساختمان",Price=2000,SubCategoryId=7 ,ImagePath = "/images/homeservice/moshavere_bazsazi_sakhteman.jpg" },
                new HomeService() { Id = 18,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "دکوراسیون و طراحی ساختمان",Price=2000,SubCategoryId=7 ,ImagePath = "/images/homeservice/dekorasion_sakhteman.jpg" },
                new HomeService() { Id = 19,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "خدمات باغبانی",Price=2000,SubCategoryId=8 ,ImagePath = "/images/homeservice/khadamat_baqbani.jpg" },
                new HomeService() { Id = 20,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "کاشت و تعویض گلدان",Price=2000,SubCategoryId=8 ,ImagePath = "/images/homeservice/kasht_goldan.jpg" },
                new HomeService() { Id = 21,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "تعمیرات مبلمان",Price=2000,SubCategoryId=9 ,ImagePath = "/images/homeservice/tamirat_mobleman.jpg" },
                new HomeService() { Id = 22,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "تعمیرات مبلمان اداری",Price=2000,SubCategoryId=9 ,ImagePath = "/images/homeservice/tamirat_mobleman_edari.jpg" },
                new HomeService() { Id = 23,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "تعمیر پنکه",Price=2000,SubCategoryId=10 ,ImagePath = "/images/homeservice/tamir_panke.jpg" },
                new HomeService() { Id = 24,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "نصب و تعمیر فر",Price=2000,SubCategoryId=10 ,ImagePath = "/images/homeservice/nasb_va_tamir_fer.jpg" },
                new HomeService() { Id = 25,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "تعمیر کامپیوتر و لپ تاپ",Price=2000,SubCategoryId=11 ,ImagePath = "/images/homeservice/tamir_laptop.jpg" },
                new HomeService() { Id = 26,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "مودم و اینترنت",Price=2000,SubCategoryId=11 ,ImagePath = "/images/homeservice/modem_va_internet.jpg" },
                new HomeService() { Id = 27,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "خدمات تعمیر موبایل",Price=2000,SubCategoryId=12 ,ImagePath = "/images/homeservice/tamirat_mobile.jpg" },
                new HomeService() { Id = 28,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "خدمات خرید موبایل و کالاهای دیجیتال",Price=2000,SubCategoryId= 12,ImagePath = "/images/homeservice/khadamt_kharid_mobile.jpg" },
                new HomeService() { Id = 29,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "خدمات دوربین",Price=2000,SubCategoryId=12 ,ImagePath = "/images/homeservice/khadamat_dorbin.jpg" },
                new HomeService() { Id = 30,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "اسباب کشی با خاور و کامیون",Price=2000,SubCategoryId=13 ,ImagePath = "/images/homeservice/asbabkeshi_ba_khavar.jpg" },
                new HomeService() { Id = 31,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "اسباب کشی با وانت و نیسان",Price=2000,SubCategoryId=13 ,ImagePath = "/images/homeservice/asabkeshi_ba_neysan.jpg" },
                new HomeService() { Id = 32,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "کارگر جابه جایی",Price=2000,SubCategoryId=13 ,ImagePath = "/images/homeservice/kargar_jabejayi.jpg" },
                new HomeService() { Id = 33,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "تعویض باتری خودرو",Price=2000,SubCategoryId=14 ,ImagePath = "/images/homeservice/taviz_batri_khodro.jpg" },
                new HomeService() { Id = 34,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "باتری به باتری",Price=2000,SubCategoryId=14 ,ImagePath = "/images/homeservice/batri_be_batri.jpg" },
                new HomeService() { Id = 35,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "حمل خودرو",Price=2000,SubCategoryId=14 ,ImagePath = "/images/homeservice/haml_khodro.jpg" },
                new HomeService() { Id = 36,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "تعویض وایر و شمع خودرو",Price=2000,SubCategoryId=14 ,ImagePath = "/images/homeservice/taviz_vayer_sham_khodro.jpg" },
                new HomeService() { Id = 37,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "براشینگ موی بانوان",Price=2000,SubCategoryId=15 ,ImagePath = "/images/homeservice/berashing_moye_banovan.jpg" },
                new HomeService() { Id = 38,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "کوتاهی موی بانوان",Price=2000,SubCategoryId=15 ,ImagePath = "/images/homeservice/kotahi_moye_banovan.jpg" },
                new HomeService() { Id = 39,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "بافت موی بانوان در خانه",Price=2000,SubCategoryId=15 ,ImagePath = "/images/homeservice/baft_moye_banovan.jpg" },
                new HomeService() { Id = 40,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "مراقبت و نگهداری",Price=2000,SubCategoryId=16 ,ImagePath = "/images/homeservice/moraqebat_negahdari.jpg" },
                new HomeService() { Id = 41,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "معاینه پزشکی",Price=2000,SubCategoryId=16 ,ImagePath = "/images/homeservice/moayene_pezeshki.jpg" },
                new HomeService() { Id = 42,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "پیراپزشکی",Price=2000,SubCategoryId=16 ,ImagePath = "/images/homeservice/pirapezeshki.jpg" },
                new HomeService() { Id = 43,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "پت شاپ",Price=2000,SubCategoryId=17 ,ImagePath = "/images/homeservice/petshop.jpg" },
                new HomeService() { Id = 44,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "خدمات دامپزشکی در محل",Price=2000,SubCategoryId=17 ,ImagePath = "/images/homeservice/khadamat_dampezshki.jpg" },
                new HomeService() { Id = 45,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "کلاس یوگا در خانه",Price=2000,SubCategoryId=18 ,ImagePath = "/images/homeservice/khadamt_yoga.jpg" },
                new HomeService() { Id = 46,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "کلاس پیلاتس در خانه",Price=2000,SubCategoryId=18 ,ImagePath = "/images/homeservice/kelas_polates.jpg" },
                new HomeService() { Id = 47,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "پیشنهاد فروش خدمات آچاره به شرکت ها",Price=2000,SubCategoryId=19 ,ImagePath = "/images/homeservice/khadamat_achare.jpg" },
                new HomeService() { Id = 48,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "استخدام نیروی خدمتکار",Price=2000,SubCategoryId=20 ,ImagePath = "/images/homeservice/estekhdam_niroye_khedmatkar.jpg" },
                new HomeService() { Id = 49,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "تعمیرات لباس",Price=2000,SubCategoryId=21 ,ImagePath = "/images/homeservice/tamirat_lebas.jpg" },
                new HomeService() { Id = 50,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "دوخت لباس زنانه",Price=2000,SubCategoryId=21 ,ImagePath = "/images/homeservice/dokht_lebas_zanane.jpg" },
                new HomeService() { Id = 51,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "تعمیر کیف و کفش",Price=2000,SubCategoryId=21 ,ImagePath = "/images/homeservice/tamir_kifokafsh.jpg" },
                new HomeService() { Id = 52,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "کیک و شیرینی",Price=2000,SubCategoryId=22 ,ImagePath = "/images/homeservice/keyko_shirini.jpg" },
                new HomeService() { Id = 53,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "دکور تولد",Price=2000,SubCategoryId=22 ,ImagePath = "/images/homeservice/dekor_tavalod.jpg" },
                new HomeService() { Id = 54,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "گل آرایی",Price=2000,SubCategoryId=22 ,ImagePath = "/images/homeservice/gol_arayi.jpg" },
                new HomeService() { Id = 55,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "فینگرفود",Price=2000,SubCategoryId=22 ,ImagePath = "/images/homeservice/finger_food.jpg" },
                new HomeService() { Id = 56,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "آموزش زبان های خارجی",Price=2000,SubCategoryId=23 ,ImagePath = "/images/homeservice/amozesh_zaban_khareji.jpg" },
                new HomeService() { Id = 57,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "آموزش ابتدایی تا متوسطه",Price=2000,SubCategoryId=23 ,ImagePath = "/images/homeservice/ebtedayi_motevasete.jpg" },
                new HomeService() { Id = 58,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "کوتاهی موی کودک",Price=2000,SubCategoryId=24 ,ImagePath = "/images/homeservice/kotahi_moye_kodak.jpg" },
                new HomeService() { Id = 59,CreatedAt = new DateTime(2025, 2, 2),  IsDeleted = false,VisitCount=210,Description=" به هزینه سفارش بعد از ساعت 21، مبلغ 150.000 تومان کمک هزینه رفت و آمد افزوده خواهد شد.", Title = "طراحی و دیزاین اتاق کودک",Price=2000,SubCategoryId=24 ,ImagePath = "/images/homeservice/tarahi_otaq_kodak.jpg" },
            }); 





        }
    }
}
